### ISSUE TITLE
Unrecognized HTML 5 elements raise invalid tag errors

### ISSUE THREAD

**Issue by csarven** [ruby-rdf/rdf-rdfa#21]
Tested at http://rdf.greggkellogg.net/distiller

`<data about="" property="http://example.org/foo" data="4">6</data>`

throws `Errors found during processing <>: Tag data invalid`

Same error for some other elements eg `source`, `track`.

Reproduce using form input or URL: http://csarven.ca/this-paper-is-a-demo

**Comment by gkellogg** [comment]
Unfortunately, Nokogiri doesn't recognize HTML5 elements; I've added a filter for the data, source and track elements, in addition to others that were reported.

Released in 1.99.1 and 2.0.0.beta2.

**Comment by csarven** [comment]
Some more (inline SVG) you might want to consider adding:

```
Errors found during processing

<>: Tag svg invalid

Tag g invalid

Tag line invalid

Tag circle invalid
```

... I suppose anything under svg will throw an error.

**Comment by csarven** [comment]
```
<https://dokie.li/acm-sigproc-sp>: Tag math invalid
Tag mi invalid
Tag mrow invalid
Tag mo invalid
Tag mn invalid
Tag mtable invalid
Tag mtr invalid
Tag mtd invalid
Tag munder invalid
Tag mstyle invalid
Tag munderover invalid
Tag msub invalid
Tag msubsup invalid
Tag msup invalid
Tag mfrac invalid
```

I acknowledge that it is not particularly fun to catch these one by one. Would it be possible simpler to omit unrecognised tags?

**Comment by gkellogg** [comment]
Yeah, this is a pain. Probably what we need to do is to use the Nokogumbo gem when we're dealing with HTML5. I spent some time on this at one point, but got stuck.

The only other alternative is to enumerate all known good element names, or not generate any warnings for bad element names.

Where do these terms come from?

Note that this is only a problem when validating.

**Comment by csarven** [comment]
I'm primarily using http://rdf.greggkellogg.net/distiller to double check things on my HTML5 Polyglot documents. Nothing particularly fancy going. Just running into some elements here and there and pinging here :) I presume https://github.com/ruby-rdf/rdf-rdfa/commit/8d469497777fd3a4b63e274b229b79b8bb44c9ee didn't yet make its way up there because I'm still getting the same errors. Thanks for the update.

**Comment by gkellogg** [comment]
Not yet, I'll update the distiller (and linter) shortly and report back on this issue.

**Comment by gkellogg** [comment]
Okay, updated now.

**Comment by csarven** [comment]
Looks good to me :+1:

**Comment by csarven** [comment]
Is there a regression bug? I'm seeing a bunch of "Tag *x* invalid"s eg., http://csarven.ca/linked-data-notifications (Input: RDFa)

**Comment by gkellogg** [comment]
@csarven No, the Gem is now using Nokogumbo for parsing HTML5, and when run on my machine it parses without error. However, it does generate an error on rdf.greggkellogg.net/distiller, which indicates that for some reason it's not picking up the Nokogumbo gem in that build environment, and is falling back to Nokogiri, which reports these tags as errors.

Note, however, that validating the doc at validator.w3.org does show markup errors. The [Linter](http://linter.structured-data.org) also shows a number of warnings, but not due to markup errors.

I'll investigate why the distiller isn't running properly.

**Comment by gkellogg** [comment]
There is some issue with Nokogumbo on Heroku which seems to be interfering with this. Runs fine when installed on my Mac. I mentioned in https://github.com/rubys/nokogumbo/issues/25#issuecomment-305652420

**Comment by gkellogg** [comment]
The fix was to downgrade nokogumbo. It's running better now, still getting some errors, which are likely legitimate HTML5 content model errors:

```
Errors found during processing
<http://csarven.ca/this-paper-is-a-demo>: @284:41: That tag isn't allowed here  Currently open tags: html, body, main, article, div, section, div, section, div, audio..
</source>
^
@287:41: That tag isn't allowed here  Currently open tags: html, body, main, article, div, section, div, section, div, audio..
</track>
^
@305:41: That tag isn't allowed here  Currently open tags: html, body, main, article, div, section, div, section, div, video..
</source>
^
@308:41: That tag isn't allowed here  Currently open tags: html, body, main, article, div, section, div, section, div, video..
</track>
```

**Comment by csarven** [comment]
Looks good, thank you!

source and target should not have end tags. Fixed.

Shouldn't the RDFa parser look the other way for the content model errors? Perhaps a warning is more suitable?

**Comment by gkellogg** [comment]
Errors are passed through from Nokogumbo when you set the `validate` option. The idea is that errors found in the markup may affect your output, there's not a reasonable way to filter these out, but validation is optional.
