### ISSUE TITLE
allow haml 5.0

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf-rdfa#23]
This uses Erubi instead of Erubis.  Erubis is deprecated in Rails 5.1.

**Comment by gkellogg** [comment]
Not sure how Erubis/Erubi plays into this; the gem uses Haml, and your patch seems to allow the use of haml 5 vs `~> 4.x`.

For the Haml bit, seems to me we could just go to `~> 5.x` unless preserving 4.x is necessary for earlier Rails versions.

**Comment by jcoyne** [comment]
@gkellogg Haml 5 adds support for Erubi. Haml 4 is Erubis only.  I don't see any problem if you want to only allow 5.x.

**Comment by abrisse** [comment]
@gkellogg: I think we can close this issue
