### ISSUE TITLE
`Statement is invalid` while loading graph

### ISSUE THREAD

**Issue by paranoicsan** [ruby-rdf/rdf-rdfa#29]
Consider the HTML markup containing such line
```html
<div vocab="http://schema.org/" typeof="MusicPlaylist"></div>
```
Getting `Statement is invalid` error [here](http://rdf.greggkellogg.net/distiller?command=serialize):
```
<>html/body/div: statement <> <http://www.w3.org/ns/rdfa#usesVocabulary> <http://schema.org/> .
   is invalid
```
But can be correctly handled [here](https://rdfa.info/play/)

**Comment by gkellogg** [comment]
The only reason it's considered invalid is that there is no base URI for the document. You can pass this with the `base_uri` option, or the `--uri` option to the `rdf` shell command, or set it in the document.

It will generate an output if you don't validate, but validation is the default when generating N-Triples. Try it in the distiller using  http://rdf.greggkellogg.net/distiller?command=serialize&format=rdfa&output_format=turtle&url=http:%2F%2Fexample%2F

**Comment by paranoicsan** [comment]
@gkellogg thanks for the clarification! Will close the issue as solved then.
