### ISSUE TITLE
hard dependency on nokogumbo

### ISSUE THREAD

**Issue by nvdk** [ruby-rdf/rdf-rdfa#30]
At some point after the 3.0 release of the linkeddata gem this gem started having a hard depedency on nokogumbo (contrary to what the readme says). Because of this it's no longer possible to include either the linkeddata gem or rdf-rdfa in non pure ruby projects.

Would you be open to removing this hard dependency?

**Comment by gkellogg** [comment]
This gem has no hard dependency, but your correct that the linkeddats gem does. The linkeddata gem is a convenience that helps the typical case, but you can achieve everything you need without it, but just requiring the specific gems you need.

The use of nokogumbo (and nokogiri) in RDFa is always a non-hard dependency.  The Gemfile includes a line to require them for testing.

If something has leaked, then of course we’ll fix that.

**Comment by nvdk** [comment]
Ah apologies I see that it is indeed the linkeddata gem itself and that this has been addressed in the latest linkeddata release. I'll retest with the latest version and open an issue on linkeddata if that's still the case. Thanks for the swift response!
